// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.6.1
// source: uber_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UberService_Todo_FullMethodName = "/api.UberService/Todo"
)

// UberServiceClient is the client API for UberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UberServiceClient interface {
	Todo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error)
}

type uberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUberServiceClient(cc grpc.ClientConnInterface) UberServiceClient {
	return &uberServiceClient{cc}
}

func (c *uberServiceClient) Todo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, UberService_Todo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UberServiceServer is the server API for UberService service.
// All implementations must embed UnimplementedUberServiceServer
// for forward compatibility
type UberServiceServer interface {
	Todo(context.Context, *TodoRequest) (*TodoResponse, error)
	mustEmbedUnimplementedUberServiceServer()
}

// UnimplementedUberServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUberServiceServer struct {
}

func (UnimplementedUberServiceServer) Todo(context.Context, *TodoRequest) (*TodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Todo not implemented")
}
func (UnimplementedUberServiceServer) mustEmbedUnimplementedUberServiceServer() {}

// UnsafeUberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UberServiceServer will
// result in compilation errors.
type UnsafeUberServiceServer interface {
	mustEmbedUnimplementedUberServiceServer()
}

func RegisterUberServiceServer(s grpc.ServiceRegistrar, srv UberServiceServer) {
	s.RegisterService(&UberService_ServiceDesc, srv)
}

func _UberService_Todo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UberServiceServer).Todo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UberService_Todo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UberServiceServer).Todo(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UberService_ServiceDesc is the grpc.ServiceDesc for UberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.UberService",
	HandlerType: (*UberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Todo",
			Handler:    _UberService_Todo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uber_service.proto",
}
